---
title: "Pairwise IPA Tests - Ery Trajectory"
author: "Mervin Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_levels: 2
---

# Libraries
```{r libs, message=FALSE, warning=FALSE}
library(SingleCellExperiment)
library(Matrix)
library(matrixStats)
library(tidyverse)
library(magrittr)
library(cowplot)
library(ggridges)
library(BiocParallel)
library(scutrboot)

register(MulticoreParam(6))
```


# Load Data
```{r load_data}
set.seed(20211018)
MIN_CELLS=50
NUM_BOOT=10000

sce <- readRDS("data/sce/hspcs.txs.full_annot.Rds")

celltypes <- c("14/Stem", "0", "3", "10", "8", "13", "11", "12/Ery")

idx_ipa <- rowData(sce) %>%
  as_tibble %>%
  group_by(gene_id) %>%
  mutate(has_ipa=any(is_ipa), has_nipa=any(!is_ipa)) %>%
  ungroup() %>%
  select(transcript_id, is_ipa, has_ipa, has_nipa) %>%
  filter(has_ipa, has_nipa) %$%
  transcript_id

# filter to tandem multiutrs
sce %<>% `[`(idx_ipa,.$clusters %in% celltypes)

gene_id2sym <- rowData(sce) %>% as_tibble %$% setNames(gene_symbol, gene_id)
```

# Two-Sample Tests
```{r partition_pairs}
test_pairs <- length(celltypes) %>% { vector("list", .*(.-1)/2) }

k <- 1
for (i in seq(1, length(celltypes)-1)) {
  for (j in seq(1, length(celltypes) - i)) {
    test_pairs[[k]] <- c(celltypes[j], celltypes[i+j])
    k <- k + 1
  }
}
```

```{r angle_tests}
res <- bplapply(test_pairs, function (p) {
  testTwoSample(sce, assayName="normcounts",
                sampleKey="clusters", geneKey="gene_id",
                sample0=p[[1]], sample1=p[[2]], 
                statistic="UI", featureIndex="is_ipa",
                nBootstraps=NUM_BOOT, minCellsPerGene=50) %>%
    as_tibble() %>%
    mutate(start=p[[1]], end=p[[2]]) %>%
    select(gene, start, end, stat, pval, bootstraps)
})

df_tests <- do.call(rbind, res) %>%
  mutate(gene_symbol=gene_id2sym[gene]) %>%
  select(gene_symbol, everything())

df_tests %>% arrange(pval) %>% head(50) %>% knitr::kable()
```

```{r hist_pvals}
hist(df_tests$pval, breaks=40, xlab="p-value",
     main="Distribution of p-values for Two-Sample IPA Tests")
```

```{r hists_by_pair, fig.width=8, fig.height=12}
df_tests %>%
  mutate(test_pair=str_c(start, " vs ", end)) %>%
  ggplot(aes(x=pval, y=test_pair)) +
  geom_density_ridges(stat='binline', bins=40, scale=0.95) +
  labs(x="p-value", y=NULL, title="IPA Tests") +
  theme_minimal_vgrid()
```

# Export
```{r export}
sprintf("data/dtu/%s-ery-trajectory-pairwise-ipa-tests.min50.boot10k.tsv.gz", format(Sys.time(), '%Y%m%d')) %>%
  write_tsv(x=df_tests)
```

---

# Session Info

```{r sesh_info, echo=FALSE}
sessionInfo()
```
