---
title: "Filter Gene SCE"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Apply filtering from SCE txs object to the gene-level SCE object.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(SingleCellExperiment)
```


# Data
## Loading
```{r load_data, message=FALSE}
sce_txs <- readRDS("data/sce/processed/ho18.txs.filtered.Rds")
sce_genes <- readRDS("data/sce/ho18.genes.Rds")
```

## Filtering
```{r filter_cells}
sce_genes %<>% `[`(,colnames(sce_txs))
```

## Export
```{r export_filtered}
saveRDS(sce_genes, file="data/sce/processed/ho18.genes.filtered.Rds")
```


---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
