---
title: "Table 1 - Compare CellRanger vs scUTRquant Clustering - Full Length"
author: "Mervin Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    toc: true
    toc_depth: 2
---

# Purpose

Generates Table 1, comparing clustering results using CellRanger versus scUTRquant
gene counts across six 10X Genomics demonstration datasets.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(SingleCellExperiment)
library(bluster)
library(Matrix)
library(DelayedArray)
library(tidyverse)
library(magrittr)
library(writexl)
```

## Parameters
```{r set_params}
set.seed(20211024)
```

## Functions

```{r methods}
cluster_louvain <- function (sce) {
  clusterRows(reducedDim(sce, "PCA"), NNGraphParam(cluster.fun="louvain"))
}
```

# Data
## Loading
```{r load_data, message=FALSE}
df_counts <- readRDS("data/sce/processed/df_counts_fulllength.all_genes.pca.Rds")
```

## Preprocessing
```{r prepare_data}
df_clusters <- df_counts %>%
  ## cluster
  mutate(clusters_sq=map(sce_sq, cluster_louvain),
         clusters_cr=map(sce_10x, cluster_louvain)) %>%
  
  ## compute adjusted Rand index
  transmute(sample_id, n_cells=map_int(idx_cells, length),  
            n_clusters_cr=map_int(clusters_cr, nlevels),
            n_clusters_sq=map_int(clusters_sq, nlevels),
            ari=map2_dbl(clusters_sq, clusters_cr, aricode::ARI))
```

# Clustering Results

## Print Table

```{r tbl_clusters}
knitr::kable(df_clusters)
```

## Export Table

```{r export_tbl}
write_xlsx(df_clusters, "output/tables/tbl1-mm10-fulllength-clustering-ari.xlsx")
```


---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash conda_env, comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
