---
title: "Merge ARI Clustering Results"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Merges the clustering ARI tables into a single file with multiple sheets.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(writexl)
library(readxl)
```

# Data
## Loading
```{r load_data, message=FALSE}
df_sq <- read_xlsx("output/tables/tbl1-mm10-clustering-ari.xlsx")
df_fl <- read_xlsx("output/tables/tbl1-mm10-fulllength-clustering-ari.xlsx")
df_mm <- read_xlsx("output/tables/tbl1-mm10-multimapping-clustering-ari.xlsx")
```

# Export
```{r export_sheets}
write_xlsx(list(scUTRquant=df_sq, full_length=df_fl, no_multimapping=df_mm), 
           "output/tables/tbl1-mm10-clustering-ari-sheets.xlsx")
```


---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
