---
title: "IPA Genes - Atlas"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Classify genes according to usage of intronic polyadenylation (IPA) sites across
atlas of cell types.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(cowplot)
library(Matrix)
library(matrixStats)
library(SingleCellExperiment)
library(writexl)
```

## Parameters
```{r set_params}
MIN_NCELLS=50
```

## Functions

```{r methods}

```

# Data
## Loading
```{r load_data, message=FALSE}
sce <- readRDS("data/sce/merged.txs.full_annot.Rds")

df_annots <- readRDS("data/utrs/utrome_genes_annotation.Rds") %>%
  as_tibble()
```

## Preprocessing
```{r prepare_data}
sce %<>% `[`(,.$age != 'old')

## M: (cells) x (tissue, cell_type, age)
M_cell_celltype <- colData(sce)[,c('tissue', 'cell_type', 'age')] %>%
  as.data.frame() %>%
  mutate(group=paste(str_replace_all(tissue, "_", " "),
                     cell_type, age, sep=', ')) %>%
    pull(group) %>%
    fac2sparse() %>%
    t()

M_gene_tx <- rowData(sce)$gene_id %>%
  fac2sparse()

ncells_gene_celltype <- ((M_gene_tx %*% assay(sce, "normcounts")) > 0) %*% M_cell_celltype
cts_tx_celltype <- assay(sce, "normcounts") %*% M_cell_celltype
cts_gene_celltype <- M_gene_tx %*% cts_tx_celltype

idx_below_min <- (t(M_gene_tx) %*% ncells_gene_celltype) < MIN_NCELLS
pct_tx_celltype <- cts_tx_celltype / (t(M_gene_tx) %*% cts_gene_celltype)

pct_tx_celltype_filtered <- pct_tx_celltype
pct_tx_celltype_filtered[idx_below_min] <- NA
ncelltypes_pct05 <- rowSums(pct_tx_celltype_filtered >= 0.05, na.rm=TRUE)
ncelltypes_pct10 <- rowSums(pct_tx_celltype_filtered >= 0.10, na.rm=TRUE)

cts_tx <- rowSums(assay(sce, 'normcounts'))
cts_tx_gene <- as.numeric(t(M_gene_tx) %*% M_gene_tx %*% cts_tx)
pct_tx <- as.numeric(cts_tx / cts_tx_gene)

df_txs <- rowData(sce) %>%
  as_tibble() %>%
  mutate(ncelltypes_pct05=ncelltypes_pct05[transcript_id],
         ncelltypes_pct10=ncelltypes_pct10[transcript_id],
         cts_total_gene=cts_tx_gene,
         pct_total=pct_tx)
```

# Analysis

## Compute Usage Across Cell Types

```{r compute_usage}
df_ipa <- df_txs %>%
  group_by(gene_id) %>%
  summarize(atlas.is_ipa_gene=any(is_ipa & ncelltypes_pct10 > 0), .groups='drop')
```

## Combine Annotations
```{r combine_annots}
df_final <- left_join(df_annots, df_ipa, by="gene_id") %>%
  select(gene_id, gene_symbol, atlas.ncelltypes_gene, atlas.utr_type, atlas.n_utrs_no_ipa,
         atlas.is_ipa_gene, utr_lengths_tandem, utr_lengths_ipa, is_blacklisted, is_consistent)
```

## Export
```{r export}
write_xlsx(df_final, path="output/tables/ed-tbl1-mouse-utrome-gene-annotations.xlsx")
```



---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
