---
title: "Multi-UTR Genes - Mouse Atlas"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Classify genes according to usage of multiple 3' UTR isoforms across
mouse atlas of cell types.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(cowplot)
```

## Parameters
```{r set_params}
MIN_NCELLS=50
```

## Functions

```{r methods}

```

# Data
## Loading
```{r load_data, message=FALSE}
df <- read_tsv("data/utrs/mm10/utr_metadata.tsv") %>%
  filter(expressed.tx)

df_annots <- read_tsv("data/utrs/mm10/utrome_txs_annotation.tsv")

txs_idx <- df_annots %>%
  filter(atlas.ncelltypes_gene > 0) %>%
  pull(transcript_id)

df %<>%
  filter(transcript_id %in% txs_idx)
```

## Preprocessing
```{r prepare_data}
df_ncts <- df_annots %>%
  group_by(gene_id) %>%
  summarize(ncelltypes_atlas=first(atlas.ncelltypes_gene))

df_multi <- df %>%
  group_by(gene_id) %>%
  summarize(nutr_pct05=first(utr.count.celltypes.pct05.no_ipa),
            nutr_pct10=first(utr.count.celltypes.pct10.no_ipa),
            ncelltypes_pct05=max(utr.ncelltypes.pct05.no_ipa),
            ncelltypes_pct10=max(utr.ncelltypes.pct10.no_ipa),
            nutr_pct05_lbl=ifelse(nutr_pct05 > 5, "6+", as.character(nutr_pct05)),
            nutr_pct10_lbl=ifelse(nutr_pct10 > 5, "6+", as.character(nutr_pct10)),
            .groups='drop') %>%
  left_join(df_ncts, by="gene_id")
```

# Plots

## Multi-UTRs - 5% Cell Type

```{r fig_pct_05, fig.width=3, fig.height=3}
df_counts <- df_multi %>%
  group_by(nutr_pct05_lbl) %>%
  summarize(n=n())

df_multi %>%
  mutate(utr_type=ifelse(nutr_pct05 > 1, "multi", "single")) %>%
  ggplot(aes(x=nutr_pct05_lbl)) +
  geom_histogram(aes(fill=utr_type), stat='count', color='black') +
  geom_text(data=df_counts, mapping=aes(label=n, y=n+500)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  scale_fill_manual(values=c("#6E90BB", "lightgrey")) +
  labs(x="3' UTR Isoform Count", y="Number of Genes") +
  guides(fill="none") +
  theme_minimal_hgrid()

ggsave("output/figure3/ed3a-n-utr-isoforms-pct05.mca.pdf", width=4, height=4, dpi=300)
```

## Multi-UTRs - 10% Cell Type

```{r fig_pct_10, fig.width=3, fig.height=3}
df_counts <- df_multi %>%
  group_by(nutr_pct10_lbl) %>%
  summarize(n=n())

df_multi %>%
  mutate(utr_type=ifelse(nutr_pct10 > 1, "multi", "single")) %>%
  ggplot(aes(x=nutr_pct10_lbl)) +
  geom_histogram(aes(fill=utr_type), stat='count', color='black') +
  geom_text(data=df_counts, mapping=aes(label=n, y=n+500)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  scale_fill_manual(values=c("#6E90BB", "lightgrey")) +
  labs(x="3' UTR Isoform Count", y="Number of Genes") +
  guides(fill=FALSE) +
  theme_minimal_hgrid()

ggsave("output/figure3/fig3a-n-utr-isoforms-pct10.mca.pdf", width=4, height=4, dpi=300)
```


# Cell Types Expressing
## Grouped Bins
### Custom 5
```{r grouped_bins_5, fig.width=4, fig.height=4}
df_binned <- df_multi %>%
  mutate(utr_type=ifelse(nutr_pct10 > 1, "multi", "single"),
         utr_type=factor(utr_type, levels=c("single", "multi")),
         ncelltypes_bin=cut(ncelltypes_atlas, 
                             breaks=c(0,2.5, 25.5, 50.5, 99.5, 200),
                             labels=c("1-2", "3-25", "26-50", "51-99", "100+")))


## Filled Bars
df_binned %>%
  ggplot(aes(x=ncelltypes_bin, fill=utr_type)) +
  geom_bar(position='fill') +
  geom_text(aes(label=after_stat(count)), stat="count", position=position_fill(vjust=0.5)) +
  scale_fill_manual(values=c("lightgrey", "#6E90BB")) +
  scale_y_continuous(labels=scales::percent_format(), expand=rep(0,4)) +
  labs(x="Number of Cell Types Expressing",
       y="Genes", fill="UTR Type") +
  theme_bw()

ggsave("output/figure3/fig3c-ncelltypes-gene-pct10.filled-bars.mca.pdf", width=4, height=4, dpi=300)
```


---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
